import 'package:bookzbox/features/box/helpers/box_mapper.dart';
import 'package:bookzbox/features/box/models/box.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:bookzbox/features/new_box/services/publish_error.dart';

import 'package:dartz/dartz.dart';

import 'publish_service.dart';

class PublishService extends IPublishService {
  PublishService._privateConstructor();

  static final PublishService instance = PublishService._privateConstructor();

  /// Publishes the passed `Box` to Firestore.
  /// If successfull, the box is updated with the id generated by Firestore
  /// and returned.
  @override
  Future<Either<PublishError, Box>> publish(Box box) async {
    bool published = false;
    DocumentReference docRef = Firestore.instance.collection('boxes').document();

    await docRef
        .setData(BoxMapper.map(box))
        .then((_) => published = true)
        .catchError((_, st) => print(st.toString()));

    box.id = docRef.documentID;

    return (published ? right(box) : left(PublishError.TimeOut));
  }
}
